name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [created]


jobs:
  Release-solution-demo:
    uses: ./.github/workflows/release-solution-to-prod-manual.yml
    with:
      solution_name: Demo
      solution_shipping_folder: out/ship/
      solution_outbound_folder: out/solutions/
      solution_source_folder: solutions/
      solution_release_folder: out/release