name: release-solution-to-prod
# prepare for releasing to prod:
#   convert solution to managed (using a build PowerPlatform environment for the conversion)
#   upload the solution to the GitHub artifacts and deploy to the PROD environment

on:
  workflow_dispatch:
  workflow_call:
  
env:
#edit your values here
  BUILD_ENVIRONMENT_URL: ${{ secrets.NONPROD_URL }}
  PRODUCTION_ENVIRONMENT_URL: ${{ secrets.PROD_URL }}
  CLIENT_ID: ${{ secrets.APPLICATION_ID }}
  TENANT_ID: ${{ secrets.TENANT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

var:
  solution_name: 'Demo'
  solution_shipping_folder: 'out/ship/'
  solution_outbound_folder: 'out/solutions/'
  solution_source_folder: 'solutions/'
  solution_release_folder: 'out/release/'

jobs:
  convert-to-managed:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@0.4.0
      with:
        solution-folder: ${{ var.solution_source_folder}}/${{ var.solution_name }}
        solution-file: ${{ var.solution_outbound_folder}}/${{ var.solution_name }}.zip
        solution-type: Unmanaged

    - name: Import solution as unmanaged to build env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{env.BUILD_ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ env.CLIENT_SECRET}}
        tenant-id: ${{env.TENANT_ID}}
        solution-file: ${{ var.solution_outbound_folder}}/${{ var.solution_name }}.zip
        force-overwrite: true
        publish-changes: true

    - name: Export solution as managed
      uses: microsoft/powerplatform-actions/export-solution@0.4.0
      with:
        environment-url: ${{env.BUILD_ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ env.CLIENT_SECRET}}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: ${{ var.solution_name }}
        managed: true
        solution-output-file: ${{ var.solution_shipping_folder}}/${{ var.solution_name }}.zip

    - name: Upload the ready to ship solution to GH artifact store
      uses: actions/upload-artifact@v2
      with:
        name: managedSolutions
        path: ${{ var.solution_shipping_folder}}/${{ var.solution_name }}.zip

  release-to-staging:
    needs: [ convert-to-managed ]
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: out/release/

    - name: Import solution to prod env
      uses: microsoft/powerplatform-actions/import-solution@0.4.0
      with:
        environment-url: ${{env.BUILD_ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ env.CLIENT_SECRET}}
        tenant-id: ${{env.TENANT_ID}}
        solution-file: ${{ var.solution_release_folder}}/${{ var.solution_name }}.zip
        force-overwrite: true
        publish-changes: true